version: 2
jobs:
  build:
    docker:
      - image: composer:1.8

    working_directory: /src
    steps:
      - checkout

      - run:
          command: make build

      - persist_to_workspace:
          root: /src
          paths:
            - vendor

  deploy:
    docker:
      - image: eeacms/rsync:1.2

    working_directory: /src

    steps:
      - attach_workspace:
          at: /src/vendor

      - run:
          command: ls -lA && echo "Deploy step would be here"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build: {}
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
